### ISSUE TITLE
Submit a proposal for a Logo

### ISSUE THREAD

**Issue by twilson63** [twilson63/palmettoflow#1]
Add your logo to the issue and we will vote on the best one

**Comment by bryanchappell** [comment]
![palmetto1](https://cloud.githubusercontent.com/assets/6373486/6356075/f05fb6c4-bc28-11e4-9f39-84f77045680d.png)

**Comment by bryanchappell** [comment]
![palmetto2](https://cloud.githubusercontent.com/assets/6373486/6356084/fe47b1e2-bc28-11e4-8e79-bfa5569d9e64.png)

**Comment by twilson63** [comment]
I like it !!!

On Tue, Feb 24, 2015 at 1:28 PM, Bryan Chappell notifications@github.com
wrote:

> [image: palmetto2]
> https://cloud.githubusercontent.com/assets/6373486/6356084/fe47b1e2-bc28-11e4-8e79-bfa5569d9e64.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/palmettoflow/issues/1#issuecomment-75815549
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
